version: "3"
services:
  mongo:
    image: mongo
    # restart: on-failure
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - mongodb:/data/db
  api-server:
    image: akeedm/simplenodecrudapp:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    # environment:
    #   - MONGO_URI=mongodb://db:27017/mydb
    # command: npm start
    depends_on:
      - mongo
    networks: 
      - my-network
    # volumes:
    #   - .:/usr/app/
    #   - /usr/app/node_modules
    ports:
      - "3001:3001"
    # links:
    #   - database

networks:
  my-network:
    driver: bridge

volumes:
  mongodb:
    driver: local
